name: digit_dss
description: "DSS Dashboard for health campaigns"
version: 0.0.1
homepage: https://github.com/egovernments/health-campaign-field-worker-app/tree/master/packages/digit_dss
repository: https://github.com/egovernments/health-campaign-field-worker-app

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  digit_components: ^1.0.0+7
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  reactive_forms: ^14.1.0
  intl: ^0.18.0
  flutter_svg: ^2.0.8
  dart_mappable: ^4.2.0
  drift: ^2.0.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.11
  path: ^1.8.2
  drift_db_viewer: ^2.0.0
  uuid: ^3.0.6
  recase: ^4.1.0
  auto_route: ^7.8.4
  digit_data_model: ^1.0.3-dev.1
  package_info_plus: ^5.0.1
  digit_showcase: ^1.0.0
  collection: ^1.16.0
  stream_transform: ^2.1.0
  async: ^2.11.0
  dio: ^5.4.2+1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.6
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  bloc_test: ^9.1.0
  mocktail: ^1.0.2
  dart_mappable_builder: ^4.2.0
  auto_route_generator: ^7.3.2
  change_app_package_name: ^1.3.0
  isar_generator: ^3.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
